version: '3.9'

services:
  dysonsphere-io:
    image: docker.io/library/node:lts-alpine
    volumes:
      - ".:/app"
      - "${OUTPUT}:/app/out"
    working_dir: /app
    command: sh -c "npm install && npx next build && npx next export"
